Update tock-registers
Update to the most recent to resolve this error in effort to build from
the 1.66 (stable) rust toolchain.

error[E0554]: `#![feature]` may not be used on the stable release channel
  --> /home/ben/.cargo/registry/src/github.com-1ecc6299db9ec823/tock-registers-0.7.0/src/lib.rs:56:1
   |
56 | #![feature(const_fn_trait_bound)]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: remove the attribute
   |
   = help: the feature `const_fn_trait_bound` has been stable since 1.61.0 and no longer requires an attribute to enable

Signed-off-by: Ben Werthmann <ben.werthmann@gmail.com>